###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 28081
  servlet:
    context-path: /

###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework: warn
    org.apache.commons.net: debug
    org.clever: debug

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: clever-storage-server
  aop.proxy-target-class: true

  servlet: #------------------------------------------------------------ 文件上传配置
    multipart:
      enabled: true
      location: ${clever.config.local-storage-config.disk-base-path}\tmp
      file-size-threshold: 1MB
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 100MB

  http: #------------------------------------------------------------------ http配置
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: true

  jackson: #------------------------------------------------------------ jackson配置
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  resources: #------------------------------------------------ html、js、css 静态资源
    chain:
      cache: true
      gzipped: true
    cache:
      period: 31536000s
    static-locations: ['classpath:/static/']

  datasource: #----------------------------------------------------------- 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.68.132:3306/clever-storage
    username: clever-storage
    password: lizhiwei
    hikari:
      data-source-properties:
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf-8
        zeroDateTimeBehavior: convert_to_null
        useSSL: false
      auto-commit: true
      maximum-pool-size: 100
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  cloud: #------------------------------------------------------------ Spring Cloud
    consul:
      enabled: false
      host: '127.0.0.1'
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: wuhan
        instance-group: svc
        tags:
        - serviceName=${spring.application.name}
        health-check-path: '/actuator/health'
        health-check-interval: 1s

###################################################################################
### management配置
###################################################################################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - health
        - info
        - env
        - metrics
        - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      root: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 5s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 3s, 4s, 5s, 10s, 15s, 20s, 30s, 50s

###################################################################################
### mybatis-plus配置
###################################################################################
mybatis-plus:
  configuration:
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    map-underscore-to-camel-case: true
  mapper-locations: 'classpath*:**/*Mapper.xml'
  check-config-location: true
  executor-type: reuse
  global-config:
    banner: true
    sql-parser-cache: true
    db-config:
      id-type: auto
      field-strategy: not_null

###################################################################################
### clever security配置
###################################################################################
clever:
  config:
    upload-speed-limit: 1048576
    download-speed-limit: 614400
    local-storage-config:
      disk-base-path: G:\filestoragepath
      stored-node: 10.2.159.100
    ali-oss-config:
      endpoint: http://oss-cn-hangzhou.aliyuncs.com
      access-key-id: LTAIzet5zCcLaw1R
      access-key-secret: p25d2Rm3vWTus9F3nMoQIry83mUkOf
      bucket-name: clever-dev-bucket
  security:
    enable-debug: false
    sys-name: ${spring.application.name}
    wait-spring-context-init-count: 2
    default-need-authorization: true
    ignore-urls:
    - '/swagger-ui*/**'
    - '/webjars/springfox*/**'
    - '/swagger-resources*/**'
    - '/v2/api-docs'
    - '/favicon.ico'
    - '/csrf'
    - '/error'
    - '/login/captcha.png'
    - '/dist/**'
    - '/static/**'
    - '/'
    - '/*.png'
    - '/*.js'
    - '/*.css'
    - '/*.html'
    - '/actuator/**'
    - '/api/**'
    ignore-authorization-urls:
    - '/login/user_info.json'
    - '/api/**'
    hide-user-not-found-exceptions: true
    not-login-need-forward: false
    forbidden-need-forward: false
    forbidden-forward-page: '/403.html'
    session-expired-redirect-url:
    login:
      login-page: '/login.html'
      login-url: '/login.json'
      username-parameter: 'username'
      password-parameter: 'password'
      captcha-parameter: 'captcha'
      post-only: true
      json-data-submit: true
      login-success-need-redirect: false
      login-success-redirect-page: '/index.html'
      login-failure-need-redirect: false
      login-failure-need-forward: false
      login-failure-redirect-page: '/login.html'
      need-captcha: false
      need-captcha-by-login-fail-count: 3
      captcha-effective-time: 60000
      concurrent-login-count: 1
      not-allow-after-login: false
    remember-me:
      enable: true
      always-remember: false
      validity-seconds: 2592000
      remember-me-parameter-name: 'remember-me'
    login-req-aes-key:
      req-password-aes-key: '636c657665722d736563757288888888'
      req-password-aes-iv: '636c657665722d736563757266666666'
    logout:
      logout-url: '/logout.json'
      logout-success-need-redirect: false
      logout-success-redirect-page: '/login.html'

###################################################################################
### Feign配置
###################################################################################
# CommonClientConfigKey 实现
clever-security-server:
  ribbon:
    listOfServers: '127.0.0.1:28080'

















